'use client';

import { useEffect, useState } from 'react';
import { BarChart3, Download, RefreshCw } from './ui-icons';

type Report = { stats: { totalTasks: number; completedTasks: number; blockedTasks: number; totalActivities: number; hours: number; attendance: number; absent: number }; byDay: { label: string; tasks: number; activities: number }[] };

export default function AdminReportsPanel() {
  const [period, setPeriod] = useState('month'); const [report, setReport] = useState<Report | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  async function load() { setLoading(true); setError(''); try { const response = await fetch(`/api/admin/reports?period=${period}`); const result = await response.json(); if (!response.ok) throw new Error(result.error); setReport(result); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Impossible de charger le rapport.'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [period]);
  return <div className="section-page"><div className="page-heading"><div><p className="eyebrow">ADMINISTRATION</p><h1>Rapports</h1><p className="muted">Analysez l’activité réelle de votre organisation.</p></div><button className="outline-button" onClick={() => window.open(`/api/admin/reports?period=${period}&format=csv`, '_blank')}><Download size={17} /> Exporter CSV</button></div><div className="report-filters"><label>Période<select value={period} onChange={(event) => setPeriod(event.target.value)}><option value="today">Aujourd’hui</option><option value="week">Cette semaine</option><option value="month">Ce mois</option></select></label></div>{error && <div className="notice error">{error}<button onClick={load}><RefreshCw size={15} /> Réessayer</button></div>}{loading ? <div className="loading-state"><span className="spinner" /> Calcul du rapport…</div> : report && <><div className="stats-grid report-stats">{[['Tâches', report.stats.totalTasks], ['Terminées', report.stats.completedTasks], ['Bloquées', report.stats.blockedTasks], ['Activités', report.stats.totalActivities], ['Heures travaillées', report.stats.hours], ['Présences', report.stats.attendance], ['Absences', report.stats.absent]].map(([label, value]) => <div className="stat-card" key={String(label)}><span className="stat-icon"><BarChart3 size={17} /></span><strong>{value}</strong><span className="stat-label">{label}</span></div>)}</div><section className="panel report-chart"><div className="panel-heading"><div><p className="eyebrow">ÉVOLUTION</p><h3>Tâches et activités</h3></div></div><div className="chart-bars">{report.byDay.map((day) => <div className="chart-day" key={day.label}><div className="bars"><i style={{ height: `${Math.max(8, day.tasks * 14)}px` }} /><b style={{ height: `${Math.max(8, day.activities * 14)}px` }} /></div><small>{day.label}</small></div>)}</div><div className="chart-legend"><span><i /> Tâches</span><span><b /> Activités</span></div></section></>}</div>;
}
