'use client';

import { ChangeEvent, useMemo, useState } from 'react';
import { CalendarDays, Check, FileSpreadsheet, FileUp, MessageSquare, Printer, Send } from './ui-icons';

type Entry = { id: string; entryDate: string; title: string; status: string; category: { name: string }; comments?: { id: string; content: string; author: { firstName: string; lastName: string }; createdAt: string }[] };

export default function JournalExtras({ entries, admin, onRefresh, onNotice, onError }: { entries: Entry[]; admin: boolean; onRefresh: () => void; onNotice: (message: string) => void; onError: (message: string) => void }) {
  const [selected, setSelected] = useState<Entry | null>(null);
  const [comment, setComment] = useState('');
  const [month, setMonth] = useState(new Date());
  const days = useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1); const count = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return Array.from({ length: count }, (_, index) => new Date(month.getFullYear(), month.getMonth(), index + 1)); }, [month]);
  const entryDays = new Set(entries.map((entry) => entry.entryDate.slice(0, 10)));
  async function action(actionName: 'COMMENT' | 'VALIDATE' | 'REQUEST_CHANGE' | 'SUBMIT') { if (!selected) return; const response = await fetch('/api/journal/actions', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: actionName, entryId: selected.id, content: comment }) }); const result = await response.json(); if (!response.ok) { onError(result.error); return; } setComment(''); onNotice(actionName === 'COMMENT' ? 'Commentaire ajouté.' : actionName === 'VALIDATE' ? 'Entrée validée.' : actionName === 'REQUEST_CHANGE' ? 'Demande de modification envoyée.' : 'Entrée envoyée pour validation.'); onRefresh(); }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !selected) return; const form = new FormData(); form.append('entryId', selected.id); form.append('file', file); const response = await fetch('/api/journal/attachments', { method: 'POST', body: form }); const result = await response.json(); if (!response.ok) onError(result.error); else { onNotice('Pièce jointe ajoutée.'); onRefresh(); } event.target.value = ''; }
  function exportFile(format: 'pdf' | 'excel') { window.open(`/api/journal/export?format=${format}`, '_blank', 'noopener,noreferrer'); onNotice(format === 'pdf' ? 'Rapport PDF prêt à imprimer.' : 'Export Excel téléchargé.'); }
  return <><section className="journal-tools-row"><div className="panel calendar-panel"><div className="panel-heading"><div><p className="eyebrow">CALENDRIER</p><h3>{month.toLocaleDateString('fr-FR', { month: 'long', year: 'numeric' })}</h3></div><div className="calendar-nav"><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}>‹</button><CalendarDays size={18} /><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}>›</button></div></div><div className="calendar-grid">{days.map((day) => { const key = day.toISOString().slice(0, 10); const count = entries.filter((entry) => entry.entryDate.slice(0, 10) === key).length; return <button key={key} className={count ? 'calendar-day has-entry' : 'calendar-day'} onClick={() => { const first = entries.find((entry) => entry.entryDate.slice(0, 10) === key); if (first) setSelected(first); }}><span>{day.getDate()}</span>{count > 0 && <small>● {count}</small>}</button>; })}</div></div><div className="panel export-panel"><p className="eyebrow">EXPORTS</p><h3>Mon journal</h3><p className="muted">Les exports utilisent uniquement vos entrées enregistrées.</p><button className="outline-button" onClick={() => exportFile('pdf')}><Printer size={16} /> PDF imprimable</button><button className="outline-button" onClick={() => exportFile('excel')}><FileSpreadsheet size={16} /> Excel</button></div></section>{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><section className="modal panel journal-detail" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)}>×</button><p className="eyebrow">DÉTAIL DU JOURNAL</p><h2>{selected.title}</h2><p className="muted">{new Date(selected.entryDate).toLocaleDateString('fr-FR')} · {selected.category.name}</p><div className="journal-comments">{selected.comments?.map((item) => <p key={item.id}><strong>{item.author.firstName} {item.author.lastName}</strong> {item.content}</p>)}</div><label className="comment-box"><MessageSquare size={16} /><textarea value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Ajouter un commentaire…" /></label><div className="detail-actions"><button className="outline-button" onClick={() => action('COMMENT')} disabled={!comment.trim()}><Send size={15} /> Commenter</button>{selected.status === 'BROUILLON' && <button className="outline-button" onClick={() => action('SUBMIT')}><Send size={15} /> Demander validation</button>}{admin && <><button className="outline-button" onClick={() => action('REQUEST_CHANGE')}>Demander modification</button><button className="primary-button" onClick={() => action('VALIDATE')}><Check size={15} /> Valider</button></>}<label className="outline-button file-button"><FileUp size={15} /> Ajouter un fichier<input type="file" accept="application/pdf,image/jpeg,image/png,text/plain,.docx" onChange={upload} hidden /></label></div></section></div>}</>;
}
